"""add_missing_columns

Revision ID: 2f928776fcbb
Revises: c3d4e5f6a7b8
Create Date: 2026-04-02 23:24:31.004173
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f928776fcbb'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitoring_jobs', 'changes_detected',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tax_rates', sa.Column('collection_model', sa.Text(), nullable=True))
    op.add_column('tax_rates', sa.Column('taxable_amount_rule', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_rates', 'taxable_amount_rule')
    op.drop_column('tax_rates', 'collection_model')
    op.alter_column('monitoring_jobs', 'changes_detected',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
